### ISSUE TITLE
Import of fetch-mock causes bundling to fail when using with create-react-app

### ISSUE THREAD

**Issue by Ankcorn** [ovotech/data-mocks#36]
When used with Create React App it fails to bundle/ startup the dev server because of the following error.

```Module not found: Can't resolve 'core-js/modules/es6.array.copy-within' in '/xxxxxx/my_project/node_modules/fetch-mock/es5'```

Okay looks like this is an issue in fetch-mock@7.3.1

There is an issue describing a similar but not identical error here https://github.com/wheresrhys/fetch-mock/issues/419

**Comment by Ankcorn** [comment]
Okay looks like this is an issue in fetch-mock@7.3.1

**Comment by Ankcorn** [comment]
Looks like this https://github.com/wheresrhys/fetch-mock/issues/419#issuecomment-482799849 suggestion could work be a workaround but seems less than ideal

**Comment by grug** [comment]
I've got a similar fix published now :)

I'm meeting the creator of fetch-mock next week so I might try to work out how we can do a better fix for this.
