### ISSUE TITLE
npm deprecation warning for `babel-preset-es2015`

### ISSUE THREAD

**Issue by kirjai** [ovotech/data-mocks#4]
During `npm install` there's a deprecation warning thrown by `babel-preset-es2015`. The suggestion in the warning is to use `babel-preset-env` with [more info here](babeljs.io/env).
```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```

**Comment by grug** [comment]
This has already been fixed 🎉
